require_relative '../lib/models/userboxd_controller'
require_relative '../lib/models/user'
require_relative '../lib/models/opinion'
require_relative '../lib/models/film'
require_relative '../lib/models/scraper'
require_relative '../lib/concerns/findable'
require_relative '../lib/concerns/persistable'
